server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    #    url: jdbc:mysql://stage-rds.cj2uw6y4crk3.ap-northeast-2.rds.amazonaws.com:3306/stagedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #
    #    username: stagerds
    #    password: )?SYa{SLj7laTxzK#5bP8wg$JhLs
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    # 404 에러 페이지를 표시하지 않게 하고, 존재하지 않는 핸들러에 대한 예외를 발생시키도록 합니다.
  mvc:
    throw-exception-if-no-handler-found=true

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

    prefix: classpath:/templates/
    suffix: .html
    cache: false

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
  ##key추가
  file:
    upload:
      directory: src/main/resources/static/image/


  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

